### ISSUE TITLE
Error detected while processing function beancount#complete..beancount#load_accounts..beancount#query_single

### ISSUE THREAD

**Issue by filmil** [nathangrigg/vim-beancount#45]
I get this error while trying to autocomplete:

```
Error detected while processing function beancount#complete..beancount#load_accounts..beancount#query_single:
line   13:
Traceback (most recent call last):
Error detected while processing function beancount#complete..beancount#load_accounts..beancount#query_single:
line   13:
  File "<string>", line 6, in <module>
Error detected while processing function beancount#complete..beancount#load_accounts..beancount#query_single:
line   13:
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
Error detected while processing function beancount#complete..beancount#load_accounts..beancount#query_single:
line   13:
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
Error detected while processing function beancount#complete..beancount#load_accounts..beancount#query_single:
line   13:
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
Error detected while processing function beancount#complete..beancount#load_accounts..beancount#query_single:
line   13:
    errread, errwrite)
Error detected while processing function beancount#complete..beancount#load_accounts..beancount#query_single:
line   13:
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
Error detected while processing function beancount#complete..beancount#load_accounts..beancount#query_single:
line   13:
    raise child_exception
Error detected while processing function beancount#complete..beancount#load_accounts..beancount#query_single:
line   13:
OSError: [Errno 2] No such file or directory
1 line less; before #1  8 seconds ago
Press ENTER or type command to continue
```

**Comment by alexason** [comment]
Hi filmil a reinstall of beancount using pip fixed the same issue for me. Guessing it was related to a python update breaking the beancount package? Anyway all good now 👍
